# Generated by Django 4.0.3 on 2022-03-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line', models.CharField(default='###', max_length=5)),
                ('destination', models.CharField(default='', max_length=50)),
                ('next_train_time', models.DateTimeField()),
            ],
        ),
    ]
