# Generated by Django 4.0.3 on 2022-03-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departures', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departures',
            new_name='Departure',
        ),
    ]
