version: '2.15.1'

services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn meinbahn.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.4-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - static:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_volume:
  static:
