# Generated by Django 4.0.3 on 2022-05-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="routes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(default=1)),
                ("stop_id", models.CharField(default="20018107", max_length=8)),
                ("direction", models.CharField(default="RBG:71707: :R", max_length=13)),
                ("name", models.CharField(default="stop name", max_length=50)),
                ("archive", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField()),
                ("date_changed", models.DateTimeField()),
                ("date_archived", models.DateTimeField()),
            ],
        ),
    ]
