# Generated by Django 4.0.3 on 2022-05-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='routes',
            new_name='Route',
        ),
    ]
